# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e65b555fae116e8b3265cf2f323396037a94bc389b512c232e5dc2171c6dbd3c014e0aae36ec52719f7ec3e5b3e2515727d3a8019f1ae000fd05abac239f2e9

test:
  secret_key_base: 6e56c35384f48f8d0cde9d3802e3d9c70b6e67e39550cf012dfa8ee5e9c1e5553cdf3cd238e6604dfbb0b07979dbd9bd93a49ed69a6611561a33eb16ee14858b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
